### PR TITLE
x11: Fix SetGamma / Bypass SetGammaRamp when changing gamma

### PR DESCRIPTION
**Pull request by hartwork**
Hi, happy new year!

This patch is [in Gentoo Linux](https://gitweb.gentoo.org/repo/gentoo.git/tree/media-libs/libsdl/files/libsdl-1.2.15-gamma.patch) to this day and the patch author Petr Pisar [confirmed and elaborated yesterday](https://bugs.gentoo.org/889412#c1) that the patch is still needed in 2023. What do you think?

Best, Sebastian

CC #717

### CODE REVIEW

**Comment by ccawley2011** [comment]
Would it be possible to keep the `SetGammaRamp` path for video drivers that don't support `SetGamma`?

**Comment by slouken** [comment]
Yes, that seems like the right thing to do.

**Comment by hartwork** [comment]
I see. Your comment made me draft and share a new candidate for the next version of `SetGamma` with patch author Petr at https://bugs.gentoo.org/889412#c6 . If he considers it sane, I will make a new pull request, but maybe I missed or misunderstood something, let's see.

**Comment by slouken** [comment]
@hartwork, thank you. I will revert this change for now.

**Comment by slouken** [comment]
This is probably the fix you want: https://github.com/libsdl-org/SDL-1.2/commit/d4b1811edcbd2cc14b192c0dc7b4d5f25cc8864d

**Comment by hartwork** [comment]
@slouken interesting fix. Thanks for taking care!

**Comment by slouken** [comment]
You're welcome!

**Pull request merged**
