### PR TITLE
Include SDL_iconv.obj in OS/2 builds

### PR DESCRIPTION
**Pull request by ccawley2011**
This has only been compile tested.

### CODE REVIEW

**Comment by sezero** [comment]
Don't know about this one: It was never included in the build, maybe for a reason
but I don't know, and I don't have the motivation to test.

So let's not do this one for now.

**Comment by ccawley2011** [comment]
> Don't know about this one: It was never included in the build, maybe for a reason but I don't know, and I don't have the motivation to test.

`README.Watcom` claims that `testiconv` doesn't work in Windows OpenWatcom builds, but I just tried that and it works fine, so I'd assume that whatever was broken back in 2006 is fixed now.

**Comment by sezero** [comment]
Windows: OK. But OS/2 is weird. Look at core/os2/geniconv in SDL2.
It may require more to do for OS/2 than plain SDL_iconv.c (but just
guessing and without testing.)

**Comment by sezero** [comment]
If you can test and fix iconv stuff for os/2 though, that'd be _really_ welcome :)

**Comment by ccawley2011** [comment]
I'm assuming that the OS/2 iconv code in SDL2 is there to support additional codepages that would normally require a full implementation of iconv, while the built-in fallback in SDL only supports ASCII, ISO-8859-1 and Unicode. I'd imagine that this will be sufficient to ensure that the iconv functions are exported in the DLL (like they are in sdl12-compat), and that any SDL 1.2 programs that need additional code pages will need to be adapted for Windows as well, since I think the official Windows builds of SDL 1.2 (and SDL2 as well) also use the built-in conversion routines.

**Comment by sezero** [comment]
That sounds correct.

**Comment by ccawley2011** [comment]
I (eventually) figured out how to get this running under eComStation, and `testiconv` seems to work fine.

**Comment by sezero** [comment]
No changes needed, yes? (Reopened the PR.)

**Comment by ccawley2011** [comment]
> No changes needed, yes? (Reopened the PR.)

Just the ones in this PR.

**Comment by sezero** [comment]
OK then, applied. Thanks!

**Pull request merged**
