### PR TITLE
atari:video:gem refactor & small bugfixes

### PR DESCRIPTION
**Pull request by mikrosk**

### CODE REVIEW

**Comment by sezero** [comment]
Thanks

**Comment by icculus** [comment]
(Can we please get the SDL 1.2 atari people write access? It seems silly for them to have to go through the PR process for platform-specific magic we don't understand, in code we're not actively maintaining, that they're clearly passionate about.)

**Comment by slouken** [comment]
> (Can we please get the SDL 1.2 atari people write access? It seems silly for them to have to go through the PR process for platform-specific magic we don't understand, in code we're not actively maintaining, that they're clearly passionate about.)

Yes!

**Comment by icculus** [comment]
@mikrosk I'm adding you and @pmandin to this repository with write access. Check for GitHub invites in your inbox. If you are working on Atari stuff, don't make a PR, just push commits (if you're doing something significant that _isn't_ Atari stuff, please _do_ make a PR, though, so we can look at it).

If there are other people in the community that should have write access, let me know.

**Comment by mikrosk** [comment]
>  If you are working on Atari stuff, don't make a PR, just push commits (if you're doing something significant that isn't Atari stuff, please do make a PR, though, so we can look at it).

Thanks guys, I follow the same policy in other projects as well (ScummVM for instance).

**Pull request merged**
