### PR TITLE
fix dynamic bpp-target when checking for supported video modes

### PR DESCRIPTION
**Pull request by pionere**

### CODE REVIEW

**Comment by sezero** [comment]
@icculus, @slouken: Comments?

**Comment by icculus** [comment]
I don't understand why this is being changed from 7 (the last element in the array) to 6.

I'm sure this is something obvious, but an explanation would be helpful here.

**Comment by pionere** [comment]
The [6] element (second last element) is supposed to be the place for the dynamic bpp.
The [7] element (last element) is just a 'terminating' entry which must be zero, otherwise the loop might never end.
The reason it worked till now is that the [6] element is never changed and stopped the loop prematurely.

**Comment by sezero** [comment]
@icculus ?

**Pull request merged**
