### PR TITLE
Backport the NEON detection code from SDL2

### PR DESCRIPTION
**Pull request by ccawley2011**
This includes the changes from libsdl-org/SDL#4100.

### CODE REVIEW

**Comment by sezero** [comment]
Do we need the additional `SDL_HasARMNEON` along with `SDL_HasNEON`?

**Comment by slouken** [comment]
By the way, we're trying to deprecate SDL 1.2 and are not adding new features or making new releases. FYI.

**Comment by icculus** [comment]
Yeah, I would definitely not add a new API to 1.2. I'm not against bug fixes to existing code, as Linux distros and the Steam Runtime still distribute SDL 1.2, but please don't add new things.

(I hadn't realized that SDL_HasARMSIMD and SDL_HasARMNEON snuck in here with the ARM blitters before, which probably caused this confusion.)

**Comment by sezero** [comment]
This fixes issues described at https://github.com/libsdl-org/SDL/issues/4095

**Comment by slouken** [comment]
@sezero it looks like you missed the comment from @icculus, above. I'll go ahead and back out the header changes.

**Comment by sezero** [comment]
> @sezero it looks like you missed the comment from @icculus, above.

I did not.  The ARM stuff went in quite some time ago. This PR just applies
fixes and minor improvements to it

> I'll go ahead and back out the header changes.

Header changes? I.e.: You want to keep the functionality, but not add to public api?

**Comment by sezero** [comment]
Removed SDL_HasARMSIMD and SDL_HasNEON from public api as of commit bff57581bc06f

**Comment by sezero** [comment]
@ccawley2011: pushed 0f2bb578 to limit ARM SIMD/NEON detection code to
ARM-32 bits only.  (That code is for internal ARM 32 bit blitters' use
only, and it isn't enabled by default.)

Please confirm that things still work correctly at your end. (e.g. for
RiscOS)

**Pull request merged**
