### PR TITLE
Backport SDL_endian.h changes from SDL2

### PR DESCRIPTION
**Pull request by ccawley2011**

### CODE REVIEW

**Comment by sezero** [comment]
1. the SDL2 version of SDL_endian.h just now received two commits,
i.e. especially aarch64 parts of this commit is unwanted.

2. The `clang-cl`-specific `_m_prefetch` parts are possibly not needed

Even with those, the merge has little to offer - I'd like to keep this one out
(and yes I myself was first tempted at a very similar merge but then quit.)
@icculus, @slouken: My vote is not to merge. Comments?

**Comment by ccawley2011** [comment]
I dropped the bits you mentioned, but this PR still offers improvements since `__builtin_bswap16`, `__builtin_bswap32` and `__builtin_bswap64` is now used on all architectures when available, not just AArch64.

**Comment by sezero** [comment]
> I dropped the bits you mentioned, but this PR still offers improvements since `__builtin_bswap16`, `__builtin_bswap32` and `__builtin_bswap64` is now used on all architectures when available, not just AArch64.

@icculus, @slouken: Comments?

If we are to merge it though, I'd suggest keeping `_SDL_HAS_BUILTIN` macro
private to `SDL_endian.h` and undefine it at the end among others (i.e. see
sdl12-compat which does that.)

**Comment by icculus** [comment]
I'm fine with whatever for 1.2. Do whatever you think is best here.

**Comment by slouken** [comment]
SDL 1.2 is deprecated and we're only merging critical fixes. Please devote any 1.2 energy to improving sdl12-compat, which is planned to replace SDL 1.2 on various platforms.

**Pull request closed without merging**
